env: DEV
log_level: DEBUG

model_name: gemini-2.0-flash
google_svc_creds_file: path/to/credentials.json

github_token: your-github-personal-access-token (https://github.com/settings/tokens)

# Global exclusion patterns for files and folders - used by workspace structure and code reading tools
global_exclution_files_folders:
  - "node_modules"
  - "__pycache__"
  - ".git"
  - ".venv"
  - "venv"
  - "env"
  - "*.pyc"
  - "*.txt"
  - "*.pyo"
  - "*.pyd"
  - "*.so"
  - "*.dll"
  - "*.dylib"
  - "*.log"
  - "*.tmp"
  - "*.temp"
  - "*.cache"
  - "*.lock"
  - "*.min.js"
  - "*.min.css"
  - "*.map"
  - "*.bundle.js"
  - ".DS_Store"
  - "Thumbs.db"
  - ".idea"
  - ".vscode"
  - "*.egg-info"
  - "dist"
  - "build"
  - "target"
  - "bin"
  - "obj"
  - "pyproject.toml"
  - ".env"
  - "package.json"
  - "package-lock.json"
  - ".md"
  - "yarn.lock"
  - "pnpm-lock.yaml"
  - "Cargo.lock"
  - "go.mod"
  - "go.sum"
  - "requirements.txt"
  - "Pipfile"
  - "Pipfile.lock"
  - "poetry.lock"
  - "setup.py"
  - "setup.cfg"
  - "MANIFEST.in"
  - ".gitignore"
  - ".gitattributes"
  - ".editorconfig"
  - ".prettierrc"
  - ".eslintrc"
  - "tsconfig.json"
  - "webpack.config.js"
  - "vite.config.js"
  - "rollup.config.js"
  - "jest.config.js"
  - "karma.conf.js"
  - "mocha.opts"
  - ".nycrc"
  - ".coveragerc"
  - "tox.ini"
  - "pytest.ini"
  - ".flake8"
  - ".pylintrc"
  - "mypy.ini"
  - "bandit.yaml"
  - "safety.yaml"
  - "docker-compose.yml"
  - "Dockerfile"
  - ".dockerignore"
  - "Makefile"
  - "CMakeLists.txt"
  - "build.gradle"
  - "pom.xml"
  - "composer.json"
  - "composer.lock"
  - "Gemfile"
  - "Gemfile.lock"
  - "Rakefile"
  - "mix.exs"
  - "mix.lock"
  - "pubspec.yaml"
  - "pubspec.lock"
  - "cabal.project"
  - "stack.yaml"
  - "package.yaml"
  - "shard.yml"
  - "shard.lock"
  - "vcpkg.json"
  - "conanfile.txt"
  - "conanfile.py"
  - "vcpkg-configuration.json"

# Git diff exclude patterns - customize which files/folders to exclude from git diff analysis
git_diff_exclude_patterns:
  - ":(exclude)docs/"
  - ":(exclude)uv.lock"
  - ":(exclude)**/*.md"
  - ":(exclude)README.md"
  - ":(exclude)package-lock.json"
  - ":(exclude)node_modules/"
  - ":(exclude).git/"
  - ":(exclude)dist/"
  - ":(exclude)build/"